- op: remove
  path: /status
  value: 1
- op: replace
  path: /metadata/name
  value: zerok-target
- op: replace
  path: /spec/replicas
  value: 1

- op: remove
  path: /spec/template/metadata/labels
  value: 1
- op: add
  path: /spec/template/metadata/labels
  value: {}
- op: add
  path: /spec/template/metadata/labels/owner
  value: zerok
- op: add
  path: /spec/template/metadata/labels/type
  value: playback

- op: remove
  path: /spec/selector/matchLabels
  value: 1
- op: add
  path: /spec/selector/matchLabels
  value: {}
- op: add
  path: /spec/selector/matchLabels/owner
  value: zerok
- op: add
  path: /spec/selector/matchLabels/type
  value: playback



### Instrumentation ###

- op: add
  path: /spec/template/spec/initContainers
  value: []
- op: add
  path: /spec/template/spec/initContainers/-
  value:  
    name: zerok-init
    command:
    - cp
    - -r
    - /opt/zerok/.
    - /opt/temp
    image: injection-test:0.0.1
    imagePullPolicy: Never
    volumeMounts:
    - mountPath: /opt/temp
      name: zerok-init

# - op: add
#   path: /spec/template/spec/volumes
#   value: []
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: zerok-init
    emptyDir: {}

- op: add
  path: /spec/template/spec/containers/0/command
  value: ["/bin/sh"]
- op: add
  path: /spec/template/spec/containers/0/args
  value: ["-c", "/opt/zerok/zerok-agent.sh"]
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value: 
    mountPath: /opt/zerok
    name: zerok-init
